### ISSUE TITLE
Invalid XML error in Flutter app (change constraints for xml package dependency)

### ISSUE THREAD

**Issue by MaikuB** [shamblett/xml2json#12]
Getting an invalid XML error in a Flutter app. I believe this occurring as the library is resolving to an older version of the xml package. Version 3.0.0 is the first to support dart 2, see https://github.com/renggli/dart-xml/issues/38

**Comment by shamblett** [comment]
Updated to latest XML package, re-published at version 2.0.14

**Comment by MaikuB** [comment]
works now. thanks!
