### ISSUE TITLE
Flutter Dependency Error 

### ISSUE THREAD

**Issue by RyanPrentiss** [shamblett/xml2json#15]
The current Dart SDK version is 2.0.0-dev.58.0.flutter-f981f09760.
...depends on xml2json >=3.0.0 which requires SDK version >=2.0.0 <3.0.0, version solving failed.

**Comment by shamblett** [comment]
Ok, I've relaxed the sdk constraints thus 

sdk: ">=2.0.0-dev <3.0.0"

as suggested in the Dart 2 migration docs, try this, see what mileage you get , there's not a lot else I can do, I can't pin  a general purpose package to a particular flutter dev version, the sooner flutter sorts itself out the better.

Re published at 3.0.1

**Comment by RyanPrentiss** [comment]
Works great. Thank you.
