### ISSUE TITLE
Any possibility of license other than GPL

### ISSUE THREAD

**Issue by espresso3389** [shamblett/xml2json#17]
It seems there are [several packages](https://pub.dev/packages?q=dependency%3Axml2json) depend on xml2json but they're using licenses incompatible to GPL like BSD. And also, when it comes to Flutter iOS apps, it is apparent AppStore's license is also incompatible to GPL.

Do you have any plan to change the license to BSD/MIT like license?

**Comment by shamblett** [comment]
This is a good point, this is one of my first Dart packages(2013) at the time I chose GPL unaware of the Dart preferred license which is MIT like, I use MIT for my newer packages. I'll update the license to a MIT one and re-release the package in the next few days.

**Comment by shamblett** [comment]
License updated to MIT license, package re-published at 4.0.0 to indicate a clear break.
