### ISSUE TITLE
Update for xml dependency

### ISSUE THREAD

**Issue by sageata** [shamblett/xml2json#20]
I am using both xml2json, to which I would like to thank you for creating, and also flutter_svg: 1.8.0. The previous flutter_svg version does not work on flutter dev channel, therefore I need to upgrade it. However, I get this error when I do.

Because no versions of xml2json match >4.2.0 <5.0.0 and xml2json 4.2.0 depends on xml ^3.0.0, xml2json ^4.2.0 requires xml ^3.0.0.

And because flutter_svg >=0.18.0 depends on xml ^4.1.0, xml2json ^4.2.0 is incompatible with flutter_svg >=0.18.0.

So, because my_app depends on both flutter_svg ^0.18.0 and xml2json ^4.2.0, version solving failed.
pub get failed (1; So, because my_app depends on both flutter_svg ^0.18.0 and xml2json ^4.2.0, version solving failed.)
exit code 1

Would be possible to get the xml dependency updated to latest version in order to fix this one?

Thank you!

**Comment by shamblett** [comment]
Yes its possible, your issue was raised just as I was going on to another task so I've done it now. Package republished at 4.2.1 with xml dependency now latest(4.2.0). I'll leave this open while you test.

**Comment by sageata** [comment]
Wow, that was quick!

Thank you, it works now :)
