### ISSUE TITLE
Backslash added when xml contains Ampersand

### ISSUE THREAD

**Issue by JadSingh** [shamblett/xml2json#21]
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<soap:Body><FODownloadHerdResponse xmlns="http://localhost/MobileTCSWebService/MobileTCSService.asmx/">
<FODownloadHerdResult>
<xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
<xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:UseCurrentLocale="true">
<xs:complexType><xs:choice minOccurs="0" maxOccurs="unbounded">
<xs:element name="Members"><xs:complexType>
<xs:element name="mem_name" type="xs:string" minOccurs="0"/>
**<mem_name>I J &amp; J M DEACON</mem_name>**

Notice mem_name has an ampersand in the name. The output for this is **I J &#92;& J M DEACON**. it adds the backslash before the & in the name. i'm using the parker transformer.

**Comment by shamblett** [comment]
Yes, it does seem to do this, I'll have a look at this.

**Comment by shamblett** [comment]
OK, I'v added a fix for this, it passes unit testing but could you please test this. Upgrade to the latest version, 4.3.0.

**Comment by JadSingh** [comment]
Thank you, that seems to have fixed the issue.
