### ISSUE TITLE
Hi my english is bad so sorry. Im having a problem with  Flutter

### ISSUE THREAD

**Issue by loli-lover-jpg** [shamblett/xml2json#22]
Im having a Problem with flutter 
The following NoSuchMethodError was thrown while handling a gesture:
The getter 'text' was called on null.
Receiver: null
Tried calling: text

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      BasicAppbarExample.build.<anonymous closure> (package:flutte/main.dart:47:58)
#2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
#3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#64be7
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(293.0, 51.0)
  finalLocalPosition: Offset(29.0, 27.0)
  button: 1
  sent tap down

this is my code 
`import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(
   home: BasicAppbarExample(),
));

class BasicAppbarExample extends StatelessWidget {
  const BasicAppbarExample({Key key}) : super(key: key);

  createAlertDialog(BuildContext context) {

    TextEditingController customController = TextEditingController();

    return showDialog(context: context,builder: (context) {
      return AlertDialog(
        title: Text('Your Name?'),
        content: TextField(
          controller: customController,
        ),
        actions: <Widget>[
          MaterialButton(
            elevation: 5.0,
            child: Text('submit'),
            onPressed: () {},
          )
        ],
      );
      });
  }

  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.redAccent,
        leading: Icon(Icons.tag_faces),
        title: Text('System App'),
        actions: <Widget>[
          IconButton(
            icon: Icon(Icons.warning),
            onPressed: () {

              var customController;
              Navigator.of(context).pop(customController.text.toString());

            },
          ),
          PopupMenuButton(
            itemBuilder: (BuildContext context) {
              return [
                PopupMenuItem(child: Text('Format')),
                PopupMenuItem(child: Text('Infect My Phone'))
              ];
            },
          )
        ],
      ),
      body: Center(child: Text('Hello')),
    );
}
}`

**Comment by shamblett** [comment]
Sorry but I don't see what any of this has to do with this package, this is a flutter problem.
