### ISSUE TITLE
type of variable

### ISSUE THREAD

**Issue by iamir4g** [shamblett/xml2json#26]
hi I get post request to the server and get a response in XML,in my XML I have int and double property like this :
<img width="574" alt="Screen Shot 1399-09-27 at 09 38 29" src="https://user-images.githubusercontent.com/10659860/102689111-e5f6d180-4210-11eb-9a0a-a9c9391074ec.png">
 `hardwareId` and `Ypoint  Xpoint`
after convert to json hardwareId is an double but must be an int?

this is my code :
```
final myTransformer = Xml2Json(); 

final respons = await http.post(
        'my Url',
        headers: {'Content-Type': 'text/xml;charset=UTF-8'},
        body: xmlBody);
    myTransformer.parse(respons.body);
    var jsonString = myTransformer.toGData();
    print('aa:');
    print(jsonString);
```

**Comment by shamblett** [comment]
I think this mis an effect of where you are running the package, from the JSON docs -
```
The precise treatment of the “integer” type may depend on the implementation of your JSON Schema validator. JavaScript (and thus also JSON) does not have distinct types for integers and floating-point values. Therefore, JSON Schema can not use type alone to distinguish between integers and non-integers. The JSON Schema specification recommends, but does not require, that validators use the mathematical value to determine whether a number is an integer, and not the type alone. Therefore, there is some disagreement between validators on this point.
```
If you are running the code above in the browser you are at the mercy of the javascript engine you are using, if you are using the VM it will be the dart implementation of toJSON that defines this, either way if you know these should be integers you could convert them manually.
