### ISSUE TITLE
Backslash added when XML contains an apostrophe 

### ISSUE THREAD

**Issue by royabousamra** [shamblett/xml2json#28]
Whenever there's an apostrophe ('), a backslash (\\) is being added before it (using toParker()). 

Input/XML: "It's a bug."
Output/JSON: "It\\'s a bug."

Using xml2json 4.4.0

**Comment by shamblett** [comment]
OK I've tested a fix for this but I need to do a bit more testing across all the transforms, problems seem to creep in with edge cases where we have 'Input/XML: "It's a bug, it's not a bug." where the two apostrophes can delineate a quoted string whilst also mixing this with double quoted strings.

**Comment by shamblett** [comment]
Should be OK now, package released at version 5.0.0

**Comment by royabousamra** [comment]
version 5.0.0 works great, thank you.
