### ISSUE TITLE
Wrong Conversion

### ISSUE THREAD

**Issue by ElieDouaihy3** [shamblett/xml2json#48]
By trying the following code :
--------------------------------
code -->https://justpaste.it/8q8qh
--------------------------------
it is converted to 
{SubItems: {Item: {Value: 3, LinkTo: [1000029214, 1000029214, 1000029214, 1000029214]}}}

while it should be
{SubItems: {Item": {Value": ["1","2","","3"],"LinkTo": ["1000029214","1000029214","1000029214","1000029214"],}}}

Thank you,
Kind Regards

**Comment by ElieDouaihy3** [comment]
`import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:xml2json/xml2json.dart';

class xmlTest extends StatelessWidget {
  const xmlTest({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    String convertStr = "<SubItems>"
    " <Item>"
    "   <Value>1</Value>"
    "   <LinkTo>1000029214</LinkTo>"
    "   <Value>2</Value>"
    "   <LinkTo>1000029214</LinkTo>"
    "   <Value></Value>"
    "   <LinkTo>1000029214</LinkTo>"
    "   <Value>3</Value>"
    "   <LinkTo>1000029214</LinkTo>"
    " </Item>"
    "</SubItems>";

    void convertFunc(){
      final myTransformer = Xml2Json();
      myTransformer.parse(convertStr);

      // print(response.body);
      var json = jsonDecode(myTransformer.toParkerWithAttrs());
      print(json);
    }

    return Scaffold(
      body:Center(
        child:TextButton(
          child:Text(
            "Result"
          ),
          onPressed:(){
            convertFunc();
          },
        ),
      ),
    );
  }
}
`

**Comment by ElieDouaihy3** [comment]
By using 
`final myTransformer = Xml2Json();
myTransformer.parse(convertStr);
print(myTransformer.toGData());`

return 
I/flutter ( 6059): {"SubItems": {"Item": {"Value": [{"$t": "1"}, {"$t": "2"}, {}, {"$t": "3"}], "LinkTo": [{"$t": "1000029214"}, {"$t": "1000029214"}, {"$t": "1000029214"}, {"$t": "1000029214"}]}}}

but with   
`  var json = jsonDecode(myTransformer.toParkerWithAttrs());`

return {SubItems: {Item: {Value: 3, LinkTo: [1000029214, 1000029214, 1000029214, 1000029214]}}}

**Comment by shamblett** [comment]
OK thanks, I'll have a look at this, why are you using Parker with Attrs BTW, what does just Parker give you? Parker and GData transforms are different and expect to be.

**Comment by shamblett** [comment]
Should be fixed now, package re released at version 5.3.4

**Comment by ElieDouaihy3** [comment]
yes it was fixed thank you

**Comment by shamblett** [comment]
Fixed
