### ISSUE TITLE
Exhausted heap space, trying to allocate 134324456 bytes.

### ISSUE THREAD

**Issue by alijamal6459** [shamblett/xml2json#53]
im getting this error after trying to read a 64mb xml file.

this is my code:
 

> final checkExist = await File(await epgXmlPath).exists();
>       if (checkExist == false) {
>         print('# xml file doesnt exist, downloading...');
>         await download();
>       }
>       print('# 1. reading xml file...');
>       var content = File(await epgXmlPath).readAsStringSync();
>       print('# 2. parsing...');
>       xml2Json.parse(content);
>       print('# 3. xml2json Bagerfish transformer...');
>       var jsonString = xml2Json.toBadgerfish(useLocalNameForNodes: true);
>       print('# 4. json decoding...');
>       var decode = jsonDecode(jsonString);
>       print('# 5. mapping json decode to EpgModel List...');
>       final epgList = (decode['tv']['programme'] as List)
>           .map((x) => EpgModel.fromJson(x))
>           .toList();
>       print('# Done!');
>       state = epgList;

this is the error:

> E/DartVM  ( 3443): Exhausted heap space, trying to allocate 134324456 bytes.
> I/flutter ( 3443): Out of Memory

**Comment by shamblett** [comment]
At what step are you getting the error? Could post the input file.

**Comment by alijamal6459** [comment]
> At what step are you getting the error? Could post the input file.

> var jsonString = xml2Json.toBadgerfish(useLocalNameForNodes: true);

ui freezes too as im displaying a circularprogressindicator during this process

**Comment by shamblett** [comment]
Ok, still need the input file so I can try to reproduce the fault.

**Comment by shamblett** [comment]
No further updates, closing.

**Comment by alijamal6459** [comment]
Guessing issue was related to allocated memory of the emulator on debug
