### ISSUE TITLE
< symbol cause parsing error

### ISSUE THREAD

**Issue by ElieDouaihy3** [shamblett/xml2json#56]
any symbol < as data is causing parsing error 

`  TextButton(
                        onPressed:(){
                          final Xml2Json myTransformer = Xml2Json();
                          myTransformer.parse("<a>aaaa<aaaaa</a>");
                        },
                        child:const Text("parse")
                    ),`

for success parsing it needs to be :

`TextButton(
                        onPressed:(){
                          final Xml2Json myTransformer = Xml2Json();
                          myTransformer.parse("<a>aaaa&lt;aaaaa</a>");
                        },
                        child:const Text("parse")
                    ),`

if it can be handled please ,
package that handle that is https://pub.dev/packages/xml_parser it doesn't give parsing error on the first example

**Comment by shamblett** [comment]
Ok thanks I'll have a look at this.

**Comment by shamblett** [comment]
Putting the debugger on this shows that the xml package that this package uses throws the following exception -
```
XmlParserException: ">" expected at 1:14
```

I'm loath to change to using the xml_parser package without very good reason.

I can look at preprocessing the input string to check for unbalanced '<,>' tags and substitute 'lt.gt' before passing it to the xml package, see how that goes.

**Comment by shamblett** [comment]
Unfortunately this is not really doable, it looks as though your test string should be encoded as CDATA really, the test below works -
```
test('< in CDATA', () {
    final testString = '<?xml-stylesheet type="text/xsl" href="xml2json.xslt"?>'
        '<reports xmlns="http://www.w3.org/2005/Atom" '
        'xmlns:georss="http://www.georss.org/georss">'
        '<![CDATA[<a>aaaa<aaaaa</a>]]>'
        '<entry></entry></reports>';
    final Xml2Json myTransformer = Xml2Json();
    myTransformer.parse(testString);
  });
```

You could try raising this issue on the xml package. I'm open to any other suggestions you may have.

**Comment by ElieDouaihy3** [comment]
no problem , I was able to solve the problem by doing some changes based on the data returned.
thank you
