### ISSUE TITLE
new added characters when parsing multiline string 

### ISSUE THREAD

**Issue by ElieDouaihy3** [shamblett/xml2json#57]
Steps to reproduce :
By using the following code 
`ElevatedButton(
                      onPressed:(){
                        String s1 = '''<a>
                        This is a 
                        multi-line
                        string 
                        </a>''';
                        final Xml2Json myTransformer = Xml2Json();
                        myTransformer.parse(s1);
                        log(myTransformer.toParker());
                      },
                      child:const Text(
                          "Parse"
                      ),
                    ),`
parsing is as follow:
[log] {"a": "                        This is a \\\\n                        multi-line\\\\n                        string \\\\n                        "}

new characters  \\\\n has been added , and in the case when i'm getting it from api sometimes it appears "\r\\n" 

toParker:
[log] {"Comments": {"Entry": {"Subject": "", "CreatedBy": "Fa, Am", "CreatedOn": "4/3/2023 9:30:51 AM", "Body": "a\\r\\\\n\\r\\\\n\\r\\\\n\\r\\\\nb", "UserID": "344"}}}

`< Entry >< Subject ></ Subject>< CreatedBy >Fa, Am</ CreatedBy >< CreatedOn >4/3/2023 9:30:51 AM</ CreatedOn ><Body>a

b</ Body ><UserID>344</ UserID></ Entry>`

note : xml spaces needs to be deleted

**Comment by shamblett** [comment]
Hmm, I'm not seeing this, 
```
test('Multiline strings', () {
    final s1 = '''<a> This is a multi-line string </a>''';
    final Xml2Json myTransformer = Xml2Json();
    myTransformer.parse(s1);
    expect(myTransformer.toParker(), '{"a": " This is a multi-line string "}');
  });
```
The code however does run this method on the input string before transforming to a specific format -
```
static String escapeTextForJson(String text) {
    var text1 = text.replaceAll('\n', '\\\\n');
    text1 = text1.replaceAll(r'\', r'\\');
    text1 = text1.replaceAll(r'"', r'\"');
    text1 = text1.replaceAll('\r', '\\\\r');
    text1 = text1.replaceAll('\t', '\\\\t');
    text1 = text1.replaceAll('\b', '\\\\f');

    return text1;
  }
```

so I'm guessing this has something to do with it, what platform are you on?

**Comment by ElieDouaihy3** [comment]
![Capture_xml2json](https://user-images.githubusercontent.com/105871954/229827208-f8947802-74de-4ed0-8e97-4360292ea7f3.PNG)

here is a picture how string has to be with output , by pasting it lines lost  if you still cannot reproduce please let me know , thank you

**Comment by shamblett** [comment]
Yep OK I can reproduce this now, I'll have a closer look at this probably next week now as I'm a bit pushed at the mo.

**Comment by shamblett** [comment]
Looking at this again '/n' in normal text is represented as '//n' in JSON text is it not, see [here](https://www.geeksforgeeks.org/how-to-handle-newlines-in-json/), so this -
```
[log] {"a": " This is a \\n multi-line\\n string \\n "}
```
is correct is it not?

**Comment by ElieDouaihy3** [comment]
> 

yes correct but displaying it as Text will Appear as
`This is a \n multi-line\n string \n`
without breaking line

**Comment by shamblett** [comment]
Why do you think this, displaying it is not the same as transforming it , the following test -
```
test('Multiline strings', () {
    final s1 = r'''<a>This is a
    multi-line
    string </a>''';
    final Xml2Json myTransformer = Xml2Json();
    myTransformer.parse(s1);
    print(s1);
    final res = myTransformer.toParker();
    print('Undecoded : $res');
    final decoder = JsonDecoder();
    final decoded = decoder.convert(res);
    print('Decoded : $decoded');
    expect(decoded.toString(), r'{a: This is a\\n    multi-line\\n    string }');
  });
````
gives the following output -
```
<a>This is a
    multi-line
    string </a>
Undecoded : {"a": "This is a\\\\n    multi-line\\\\n    string "}
Decoded : {a: This is a\\n    multi-line\\n    string }
```
The json string output is correctly decoded back to the correct string as per the JSON standard.

The package is responsible only for generating correct JSON, not how its displayed or what you do with it next.

**Comment by ElieDouaihy3** [comment]
> Why do you think this, displaying it is not the same as transforming it , the following test -
> 
> ```
> test('Multiline strings', () {
>     final s1 = r'''<a>This is a
>     multi-line
>     string </a>''';
>     final Xml2Json myTransformer = Xml2Json();
>     myTransformer.parse(s1);
>     print(s1);
>     final res = myTransformer.toParker();
>     print('Undecoded : $res');
>     final decoder = JsonDecoder();
>     final decoded = decoder.convert(res);
>     print('Decoded : $decoded');
>     expect(decoded.toString(), r'{a: This is a\\n    multi-line\\n    string }');
>   });
> ```
> 
> gives the following output -
> 
> ```
> <a>This is a
>     multi-line
>     string </a>
> Undecoded : {"a": "This is a\\\\n    multi-line\\\\n    string "}
> Decoded : {a: This is a\\n    multi-line\\n    string }
> ```
> 
> The json string output is correctly decoded back to the correct string as per the JSON standard.
> 
> The package is responsible only for generating correct JSON, not how its displayed or what you do with it next.

Thanks, I'll try and see what I can do
