### ISSUE TITLE
Problems with CDATA

### ISSUE THREAD

**Issue by montyr75** [shamblett/xml2json#7]
When an XML text node uses the CDATA tag, all three conversion routines fail to preserve the text node in the output JSON.

Example:
`<Option Part="2" Sequence="1"><![CDATA[The same password referenced when you registered the mobile device.]]></Option>`

When converted to JSON, none of the text within the CDATA will be there.

**Comment by shamblett** [comment]
Yes, I'll look at this , I can't recall offhand whether the original algorithms I re-implemented in Dart didn't do this or whether I omitted it, however it needs looking at. I'll schedule this for early next week.

**Comment by shamblett** [comment]
Ok, just looking at this, the docs say that CDATA tags are ignored for all 3 transforms, this I believe is because of this :

'There is no XML CDATA equivalent in JSON. But you can encode your message in a string literal using something like base64.'

This is taken form this SO question :    

http://stackoverflow.com/questions/14935866/json-is-there-any-xml-cdata-equivalent

This would explain why the original standards, especially say Gdata don't support this.

Also, the CDATA XML tag description says :  

'Everything inside a CDATA section is ignored by the parser.'

So, i think the code is OK in this case.

**Comment by montyr75** [comment]
Well, there is no equivalent to a text node in JSON, either, but with some of the converters, text nodes go into JSON as a property called `$t`. And in many of the JS-based xml2json implementations, CDATA nodes are handled similarly, being added as a property in the JSON with a name like `__cdata`.

CDATA is massively prevalent in existing XML out there, so lacking this functionality makes this Dart package difficult to use. I would already have switched to using a JS tool if my code wasn't server-side Dart. As it stands, I have to write code to massage the XML before handing it off to xml2json, and it's quite messy. I might be better off just using an XML package to get at the XML data.

Anyway, I still hold out hope that you'll see the value in adding the ability to handle CDATA. Thanks for your efforts in producing the only xml2json package for Dart that I know of.

**Comment by shamblett** [comment]
Yes Ok, there is obviously a use case for this no matter what the docs say, also the xml parser the code uses does support  CDATA xml nodes in its parse tree so I can get at this data and transform it. I'll have a look at adding this this week.

**Comment by shamblett** [comment]
OK, I've added CDATA element parsing to Badgerfish and GData, I'd rather keep Parker as lightweight as possible, also I've used the __cdata tag as you suggested above so in the JSON output a CDATA tag becomes : 

"__cdata" : "This is cdata",

If this is OK I just need to do a bit of other tidying then I'll re-release this.

**Comment by montyr75** [comment]
Awesome! I look forward to the opportunity to test this out. Thanks again for your contributions to the community.

**Comment by shamblett** [comment]
OK, I've pushed version 2.0.7 to pub, please try it out, I've updated the unit tests but there's no substitute for real world testing! I'll leave this issue open for now.

**Comment by shamblett** [comment]
OK, no further issues, closing
