### ISSUE TITLE
Problem with double-quotes and CDATA

### ISSUE THREAD

**Issue by montyr75** [shamblett/xml2json#8]
Hi again! I was finally able to do some testing on your awesome changes to support CDATA in XML files, but I'm afraid there appears to be one small problem.

If there are double-quotes within a CDATA block, they are not properly escaped, so they end up in the JSON like so:

`"__cdata": "loadMovie("whatever")"`

This, of course, breaks the JSON.

**Comment by shamblett** [comment]
oops, yes, I have a function already written to do the escaping but didn't put it in the CDATA codeI'll update the code and re-publish the package.

**Comment by shamblett** [comment]
OK, done and pushed as 2.0.8, please re-test.
