### ISSUE TITLE
Blank page output Dartium webpage 'xml2json_test.html'

### ISSUE THREAD

**Issue by lubi888** [shamblett/xml2json#9]
Hi,

Firstly, the 'xml2json/test/lib/xml2json_interactive.html' is working fine in dartium. Thanks a bunch for that! It's quite helpful as I still like xml and xslt.

I could be doing something wrong but the 'xml2json_test.html' webpage comes up blank in dartium now. Ctrl+U gives

```
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8">
    <title>Xml2json</title>
    <link rel="stylesheet" href="xml2json.css">
  </head>
  <body>
    <script type="text/javascript" src="packages/unittest/test_controller.js"></script>  
    <script type="application/dart" src="xml2json_test.dart"></script>
    <script type="text/javascript" src="packages/browser/dart.js"></script>
  </body>
</html>
```

I don't know if it's related but when I open and IDE it gives a few deprecated warnings. 

`INFO|HINT|/home/iveagh/dart/xmlXslt/xml2json/test/lib/xml2json_test.dart|11|1|'unittest' is deprecated
INFO|HINT|/home/iveagh/dart/xmlXslt/xml2json/test/lib/xml2json_test.dart|12|1|'test.html_config' is deprecated
INFO|HINT|/home/iveagh/dart/xmlXslt/xml2json/test/lib/xml2json_test.dart|16|3|'useHtmlConfiguration' is deprecated
WARNING|STATIC_WARNING|/home/iveagh/dart/xmlXslt/xml2json/test/lib/xml2json_test.dart|29|54|0 positional arguments expected, but 1 found
WARNING|STATIC_WARNING|/home/iveagh/dart/xmlXslt/xml2json/test/lib/xml2json_test.dart|38|54|0 positional arguments expected, but 1 found
WARNING|STATIC_WARNING|/home/iveagh/dart/xmlXslt/xml2json/test/lib/xml2json_test.dart|47|54|0 positional arguments expected, but 1 found`

thanks for work so far...

**Comment by shamblett** [comment]
Hi, things have moved on a trice since I last looked at this, I'll run this against Dart 1.19 and see where we are.

**Comment by lubi888** [comment]
goodmorning shamb, 

that would be great if you have the time. I'm sure you're busy with lots but it would be nice if i see the tests running and see your code running again.

tks in advance.

**Comment by shamblett** [comment]
Closing, testing doesn't now use Dartium on Dart 2.0, testing updated to use webdev
